export class indices {
  readonly defalutMap: string[] = [
    "supplyType",
    "subSupplyType",
    "docType",
    "docNo",
    "docDate",
    "toTrdName",
    "toGstin",
    "toAddr1",
    "toAddr2",
    "toPlace",
    "toPincode",
    "toStateCode",
    "actToStateCode",
    "fromTrdName",
    "fromGstin",
    "fromAddr1",
    "fromAddr2",
    "fromPlace",
    "fromPincode",
    "fromStateCode",
    "actualFromStateCode",
    "productName",
    "productDesc",
    "hsnCode",
    "quantity",
    "qtyUnit",
    "taxableAmount",
    "cgstRate",
    "sgstRate",
    "igstRate",
    "cessRate",
    "cgstValue",
    "sgstValue",
    "igstValue",
    "cessValue",
    "totalValue",
    "transMode",
    "transDistance",
    "transporterName",
    "transporterId",
    "transDocNo",
    "transDocDate",
    "vehicleNo",
    "vehicleType"
  ];
  readonly defaultEwaybillItems: string[] = [
    "productName",
    "productDesc",
    "hsnCode",
    "quantity",
    "qtyUnit",
    "taxableAmount",
    "cgstRate",
    "sgstRate",
    "igstRate",
    "cessRate"
  ];
  readonly primarykey: string = "docNo";
  readonly datatype: any = {
    transDocNo: "string",
    transMode: "number",
    transDistance: "number",
    transDocDate: "string",
    vehicleNo: "string",
    VehicleType: "string",
    actualFromStateCode: "string",
    actToStateCode: "string",
    totInvValue: "number",
    supplyType: "string",
    subSupplyType: "string",
    docType: "string",
    docNo: "string",
    docDate: "string",
    fromGstin: "string",
    fromTrdName: "string",
    fromAddr1: "string",
    fromAddr2: "string",
    fromPlace: "string",
    fromPincode: "number",
    fromStateCode: "string",
    toGstin: "string",
    toTrdName: "string",
    toAddr1: "string",
    toAddr2: "string",
    toPlace: " string",
    toPincode: "number",
    toStateCode: "string",
    totalValue: "number",
    cgstValue: "number",
    sgstValue: "number",
    igstValue: "number",
    cessValue: "number",
    transporterId: "string",
    productName: "string",
    productDesc: "string",
    hsnCode: "number",
    quantity: "number",
    qtyUnit: "string",
    cgstRate: "number",
    sgstRate: "number",
    igstRate: "number",
    cessRate: "number",
    taxableAmount: "number"
  };
}
