export const TOGGLE_BULB_STATE = "TOGGLE_BULB_STATE";
export const JUMP_TO = "JUMP_TO";
export const TOGGLE_LOGO_STATE = "TOGGLE_LOGO_STATE";
export const CHANGE_BULB_LOCATION = "CHANGE_BULB_LOCATION";