export interface InvoiceItem {
    item_discount: string,
    item_tax_rate_intrastate?: string,
    item_tax_rate_interstate?:string,
    item_qty: string,
    item_tax_rate: string,
    item_rate: string,
    item_taxation_category: string,
    primary_secondary_conversion_factor: string,
    item_taxed_total: string,
    item_taxable_total: string,
    cgst: string,
    sgst: string,
    igst: string,
    cess: string,
    item_id?:string,
    item_name:string,
    item_hsn_code:string,
    item_unit: string,
    item_unit_last: string,
    item_unit_primary_actual: string,
    item_unit_primary_display: string,
    item_unit_secondary_actual: string,
    item_unit_secondary_display: string,
    item_actual_rate:string,
    item_type:string,
  }